In [44]:
import numpy as np
from sympy import *

## Question 1
Compute the inverse

In [2]:
A = np.array([
    [3,3],
    [-2,-1]
])

print(np.linalg.inv(A))

[[-0.33333333 -1.        ]
 [ 0.66666667  1.        ]]


## Question 2

Find solution to system of equations using matrix inverse


In [16]:
# Coefficents of system 
A = np.array([
    [0,5,-10],
    [1,3,-2],
    [0,4,-7,]
])

# Constants of system
b = np.array([
    [-25,-8,-18]
])

Ainv = np.linalg.inv(A)

# Ax = b -> x = A^-1 b
x = Ainv@b.T

print("A^-1=\n",Ainv)
print("x =\n",x)

A^-1=
 [[ 2.6  1.  -4. ]
 [-1.4  0.   2. ]
 [-0.8  0.   1. ]]
x =
 [[-1.]
 [-1.]
 [ 2.]]


## Question 3

Find A given two other matrices using the inverse

In [28]:
B = np.array([
    [2,-6,4],
    [-1,5,2],
    [1,-2,5]
])

C = np.array([
    [-10,-1,3],
    [-9,-3,-10],
    [-7,-8,-5]
])

# WARN: GIVEN EQAUTINO DIFFERENT EACH TIME ### 
# Isolate A, then change print statement to match equation

# A^-1 B = C <-- Given equation
# B = A C <-- multiply both sides by A (A^-1 A = 1)
# B C^-1 = A <--- multiply both sides by C^-1 to isolate A

print("A =\n", B@np.linalg.inv(C))

A =
 [[-0.09768638 -0.99742931  1.13624679]
 [ 0.37532134  0.3059126  -0.78663239]
 [ 0.17994859 -0.68894602  0.48586118]]


## Question 4

Find conditions on k that will make the matrix A invertible.

In [96]:
for k in range(-100,100):   
    A = np.array([
    [-5,5,0],
    [-9,k,6],
    [-3,1,2]
    ])  
    if np.linalg.det(A) == 0:
        print(k)
        break
    # Honestly, should never get to this, idk if this actually works if is always invertible. Idk test for if it is never invertbile. 
    if k == 99: 
        print(always)
        break

3


## Question 5

Find the inevrse of the given transformation, T

In [ ]:
T = nparr