In [1]:
import numpy as np
from sympy import *

## Question 1

 Use the ~~cofactor expansion~~ **python**
 to compute the following determinant:

In [2]:
A = np.array([
    [-3,10,-5],
    [10,4,-8],
    [-7,10,10]
])

print(np.linalg.det(A))

-1440.0000000000005


## Question 2

Find a formula in terms of k for the following determinant:

In [3]:
k = Symbol('k')

afj, bgh, cei, hfc, iga, jeb = [], [], [], [], [], []

A = np.array([
    [-1,0,7],
    [k,4,-7],
    [-1,-2,4]
])

# Only works for 3x3 matrices
# Uses the Rule of Sarrus method
def sarrus(A):
    for i in range(3):
        afj.append(A[i][i])
        hfc.append(A[2+(-1*i)][i])

    bgh.append(A[0][1])
    bgh.append(A[1][2])
    bgh.append(A[2][0])

    cei.append(A[0][2])
    cei.append(A[1][0])
    cei.append(A[2][1])

    iga.append(A[2][1])
    iga.append(A[1][2])
    iga.append(A[0][0])

    jeb.append(A[2][2])
    jeb.append(A[1][0])
    jeb.append(A[0][1])


sarrus(A)

# Double checking work
print(afj,bgh,cei,hfc,iga,jeb)

# Shows partial breakdown of A, if A is:
# [a b c]
# [e f g]
# [h i j] 
# afj + bgh + cei - hfc - iga - jeb
print(
    np.prod(afj),'+',np.prod(bgh),'+',np.prod(cei),
    '-',
    np.prod(hfc),'-',np.prod(iga),'-',prod(jeb)
    )

res = np.prod(afj) + np.prod(bgh) + np.prod(cei) - np.prod(hfc) - np.prod(iga) - np.prod(jeb)

print('')
print('det(A) in terms of k =',res)

[-1, 4, 4] [0, -7, -1] [7, k, -2] [-1, 4, 7] [-2, -7, -1] [4, k, 0]
-16 + 0 + -14*k - -28 - -14 - 0

det(A) in terms of k = 26 - 14*k


## Question 3

Let A be a 2×2 (can change) matrix and suppose that det(A)=6 (can cahnge). For each of the following row operations, determine the value of det(B), where B is the matrix obtained by applying that row operation to A (can change).

In [4]:
# Input determinant given in problem
det = 4

def operations(type, value=1):
    if type == 'scale':
        print('Multiplied a row by some scalar: det =',det * value)
    elif type == 'swap':
        print('Swaped two rows (doesn\'t matter which): det =',-1*det)
    elif type == 'add':
        print('Added one row to another (does nothing): det =',det)
    else:
        print('Types accepted: scale (needs value if so, default is 1), swap, and add')
        print('Please try again')


operations('scale',3)

operations('swap')

operations('add')

Multiplied a row by some scalar: det = 12
Swaped two rows (doesn't matter which): det = -4
Added one row to another (does nothing): det = 4


## Question 4

Compute the determinant of the matrix A, below, by using row operations to transform A to an upper-triangular matrix B. Then express the determinant of A as a multiple k of the determinant of B, and use this to compute the determinant of A.



In [18]:
# I use QR decomposition here to find upper right triangle, R

A = np.array([
    [10,-1,2,8],
    [30,-18,-11,38],
    [0,5,7,-8],
    [-60,51,27,-67]
])

Q,R = np.linalg.qr(A)

print(R)
print(' ')
print(np.linalg.det(R))
print(np.linalg.det(A))



[[-67.82329983  53.22654617  28.45629754 -77.25958503]
 [  0.         -10.8597782   -8.59774145   3.38304611]
 [  0.           0.          -4.39522154   8.96239353]
 [  0.           0.           0.           0.43246144]]
 
-1400.000000000006
1399.999999999996


## Question 5
