In [10]:
import numpy as np
from sympy import *

## 3.2 Question 1

  If A, B, and C are 3×3 matrices; and det(A) = 5, det(B) = −2, and det(C) = −1 then compute:

$det(4C^TA^TC^2B^3C^TB^{-1})$ 
 


In [11]:
# Determinants of given matrices
A, B, C = 5,-2,-1

# Size of given matrices
n = 3

# Given computation, ** = ^
print(
    4**n * C * A * C**2 * B**3 * C * B**-1
)

1280.0


## 3.2 Question 2

Compute the adjugate of the following matrix:


In [12]:
A = np.array([
    [7,0,5],
    [4,4,-6],
    [6,-6,-6]
])

# Adj(A) = A^-1 * det(A) --- Only for square matrices
print(np.linalg.inv(A)*np.linalg.det(A))

[[-60. -30. -20.]
 [-12. -72.  62.]
 [-48.  42.  28.]]


## 3.3 Question 1

Find the characteristic polynomial of A. Use x for the variable in your polynomial. You do not need to factor your polynomial.


In [13]:
x = symbols('x')

# Subtract x from diagonal elements
A = Matrix([
    [7-x,-3,-3],
    [4,-2-x,-2],
    [14,-6,-6-x]
])

A.det()

-x**3 - x**2 + 2*x

## 3.3 Question 2

Find the characteristic polynomial of A. Use x for the variable in your polynomial.


In [14]:
A = Matrix([
    [-3-x,0,-3,4],
    [0,-3-x,3,-1],
    [0,0,0-x,-1],
    [0,0,0,2-x]
])

A.det()

x**4 + 4*x**3 - 3*x**2 - 18*x

## 3.3 Question 3

List all of the distinct eigenvalues of A. Enter your answer as a list of numbers separated by commas.

In [15]:
A = np.array([
    [3,4],
    [-6,-7]
])

print(np.linalg.eigvals(A))

[-1. -3.]


## 3.3 Question 4

List all of the distinct eigenvalues of A. Enter your answer as a list of numbers separated by commas.


In [16]:
A = np.array([
    [1,-1,0],
    [0,0,0],
    [0,-2,-2]
])

print(np.linalg.eigvals(A))

[ 1. -2.  0.]


## 3.3 Question 5

Find the basic eigenvectors of A corresponding to the eigenvalue λ.

In [57]:
A = np.array([
    [-25,12,-24],
    [0,3,0],
    [28,-12,27]
])

evals,evecs = np.linalg.eig(A)

print('Eigen values =', evals)
print(' ')
print('Eigen vectors (normalized) ↓\n')
print(evecs)

print(' ')

A = Matrix(A)

A.eigenvects()[0][2][0]



Eigen values = [-1.  3.  3.]
 
Eigen vectors (normalized) =

[[-0.70710678  0.65079137  0.6882472 ]
 [ 0.          0.          0.22941573]
 [ 0.70710678 -0.7592566  -0.6882472 ]]
 


Matrix([
[-1],
[ 0],
[ 1]])

## 3.3 Question 6


## 3.3 Question 7 