In [1]:
import numpy as np
from sympy import *

## Question 1

If **u** and **v** are the vectors below, solve the following equation for the vector **x**.

Given equation:
$$ 
\begin{align*}
3(\vec{x}-3\vec{u})-2\vec{v}=2\vec{v}+\vec{u}-\vec{x}
\end{align*}
$$

In [2]:
from fractions import Fraction
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

u,v,x = symbols('u,v,x')

# Given equation -> Eq(left side, right side)
vec_eq = Eq(3*(x-3*u)-2*v, 2*v+u-x)
print(solve(vec_eq, x))
print(' ')

# Given vectors
u = np.array([[-4,3,-3]]).T
v = np.array([[5,-2,1]]).T

# Result from solve() function
x = (5/2)*u + v

print(x)


[5*u/2 + v]
 
[[-5]
 [11/2]
 [-13/2]]


## Question 2

Find the distance d between the points $P_1$ and $P_2$ by first finding the vector $\vec{v}$ from $P_1$ to $P_2$, then finding the length of $\vec{v}$. Use the square root symbol '√' where needed to give an exact value for your answer.



In [3]:
# Inputing as row vector (easeir), tranpose to make column vector
P1 = np.array([[-9,-8,1]]).T
P2 = np.array([[-7,4,4]]).T

# v = distance between points
v = P2-P1
print(f'v = {v.T[0]}.T\n')

# d = norm = length = ||v|| = (v.T@v)**0.5 = sqrt(v.T@v)
d = np.linalg.norm(v)
vTv = v.T @ v

print(f'd = sqrt({int(d**2)})\n')
print('d =', d)
print('d^2 =', int(d**2))
print('vTv =', vTv[0][0])



v = [2 12 3].T

d = sqrt(157)

d = 12.529964086141668
d^2 = 157
vTv = 157


## Question 3

Find a unit vector $\vec{u}$ with the same direction as the given vector $\vec{v}$. Use the square root symbol '√' where needed to give an exact value for your answer. 

In [4]:
v = np.array([[-9,5,10]]).T

u = v/np.linalg.norm(v)
vhat = v / (v**2).sum()**0.5

# u = vhat
print(u-vhat)
print(' ')

print(f'u= sqrt(\n{u**2})\n')
print(f'u=\n{u}')

[[0]
 [0]
 [0]]
 
u= sqrt(
[[81/206]
 [25/206]
 [50/103]])

u=
[[-622923/993403]
 [347451/997372]
 [596331/855896]]


## Question 4

Find the vector equation for the line passing through the points $P_1$ and $P_2$.

In [5]:
p1 = np.array([[-5,-9,7]]).T
p2 = np.array([[-11,-5,9]]).T

v = p2-p1
print(f't =\n{v}\n')

print('Use either p1 or p2 for vector in vector equation')

t =
[[-6]
 [4]
 [2]]

Use either p1 or p2 for vector in vector equation


## Question 5

Find the vector equation for the line passing through the point $P$ and parallel to the line given

---

Code isn't helpful for this one.

1. Input P as a vector
2. Then input all scalrs of t as a vector for the equation

E.g.,

$P(-2,4,6)$ parallel to line 

$$
\begin{align*}
x &= -3+2t \\
y &= 2-8t \\ 
z &= -6+2t 
\end{align*}
$$
Gives
$$
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -2 \\ 4 \\ 6 \end{bmatrix} + 
t \begin{bmatrix} 2 \\ -8 \\ 2 \end{bmatrix}
$$



## Question 6


Let $L_1$ be the line passing through the points $Q_1(4, 4, −1)$ and $Q_2(3,2, −2)$ and let $L_2$ be the line passing through the point $P_1(−13, −9,10)$ with direction vector $d=[−4, −2, 4]^T$ Determine whether $L_1$ and $L_2$ intersect. If so, find the point of intersection $Q$.


In [41]:
q1 = np.array([[-2,-2,-5]]).T
q2 = np.array([[-6,2,-11]]).T
d2 = q2 - q1

p1 = np.array([[-10,10,-20]]).T
d1 = np.array([[3,-1,3]]).T


print((d2.T@d1)[0][0])
print(d2)

print(

-2

-34
[[-4]
 [4]
 [-6]]


AttributeError: module 'numpy.linalg' has no attribute 'diag'

$$
L_1 = \begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -2 \\ -2 \\ -5 \end{bmatrix} + 
t \begin{bmatrix} -4 \\ 4 \\ -6 \end{bmatrix}
$$
$$
\begin{align*}
x &= -2-4t \\
y &= -2+8t \\ 
z &= -5-6t 
\end{align*}
$$
$$
L_2 = 
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -10 \\ 10 \\ -20 \end{bmatrix} + 
t \begin{bmatrix} 3 \\ -1 \\ 3 \end{bmatrix}
$$
$$
\begin{align*}
x &= -10-3t \\
y &= 10-1t \\ 
z &= -20+3t 
\end{align*}
$$


