In [513]:
import numpy as np
from scipy.linalg import *
from termcolor import colored

## Question 1

Consider the following matrix A and its reduced row-echelon form:

---

Find the dimensions of row(A), null(A), and im(A), and give a basis for each of them.

In [514]:
A = Matrix([
    [-1,3,-2,-6,-4,2],
    [-1,3,-2,-6,-4,3],
    [0,0,0,0,0,-1],
    [-1,4,-2,-9,-6,3]
])


RA = A.rowspace()
print(f'Dimeionsion of rowspace = {len(RA)}\n')
for i in range(len(RA)):
    print(np.array(RA)[i].T,'\n')
print('-'*20)

NA = A.nullspace()
print(f'Dimeionsion of nullspace = {len(NA)}\n')
for i in range(len(NA)):
    print(np.array(NA)[i],'\n')
print('-'*20)
-2  
CA = A.columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

Dimeionsion of rowspace = 3

[[-1]
 [3]
 [-2]
 [-6]
 [-4]
 [2]] 

[[0]
 [-1]
 [0]
 [3]
 [2]
 [-1]] 

[[0]
 [0]
 [0]
 [0]
 [0]
 [-1]] 

--------------------
Dimeionsion of nullspace = 3

[[-2]
 [0]
 [1]
 [0]
 [0]
 [0]] 

[[3]
 [3]
 [0]
 [1]
 [0]
 [0]] 

[[2]
 [2]
 [0]
 [0]
 [1]
 [0]] 

--------------------
Dimeionsion of columnspace = 3

[[-1]
 [-1]
 [0]
 [-1]] 

[[3]
 [3]
 [0]
 [4]] 

[[2]
 [3]
 [-1]
 [3]] 

--------------------


## Question 2

Consider the following matrix A:

[ ]

For each of the following vectors, determine whether the vector is in the column space of A. If so, demonstrate this by providing a vector x so that $A\vec{x}=\vec{b}_i$.




In [554]:
A = np.array([
    [2,2,-6],
    [1,4,-6],
    [-2,-5,9]
])

b1 = np.array([[-12,-18,24]]).T
b2 = np.array([[4,2,-4]]).T
b3 = np.array([[-10,2,-9]]).T

CA = Matrix(A).columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

# Remove linearly dependent column 
n = 3 # <--- column not found in columnsapce (starting at 1) 
#   ^ needs to be edited

B = np.delete(A,n-1,axis=1)
print(f'Matrix used to find regression coefficients ↓\n{B}\n')

# Find left inverse, use to find regression coefficients
Linv = np.linalg.inv((B.T@B))@B.T

def coefficients(A, Linv,b):
    x = np.round(Linv@b)
    x = np.array([np.insert(x,n-1,0)]).T.astype(int)
    print(f'x = \n{x}\n')
    print(f'b = \n {A@x}\n')
    print(f'Ax = b? (is b in columspace of A?) {(A@x==b).all()}\n')
    print('-'*20,)
    
# Brrrrrrrrrrrrrr, feels good 
coefficients(A,Linv,b1)
coefficients(A,Linv,b2)
coefficients(A,Linv,b3)



Dimeionsion of columnspace = 2

[[2]
 [1]
 [-2]] 

[[2]
 [4]
 [-5]] 

--------------------
Matrix used to find regression coefficients ↓
[[ 2  2]
 [ 1  4]
 [-2 -5]]

x = 
[[-2]
 [-4]
 [ 0]]

b = 
 [[-12]
 [-18]
 [ 24]]

Ax = b? (is b in columspace of A?) True

--------------------
x = 
[[2]
 [0]
 [0]]

b = 
 [[ 4]
 [ 2]
 [-4]]

Ax = b? (is b in columspace of A?) True

--------------------
x = 
[[-7]
 [ 4]
 [ 0]]

b = 
 [[-6]
 [ 9]
 [-6]]

Ax = b? (is b in columspace of A?) False

--------------------


## Question 3

Give a basis for the column space of the matrix A using only columns of A in your basis.

In [555]:
A = Matrix([
    [0,3,6,0],
    [1,-2,1,-1],
    [0,-2,-4,0]
])

CA = A.columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

Dimeionsion of columnspace = 2

[[0]
 [1]
 [0]] 

[[3]
 [-2]
 [-2]] 

--------------------


## Question  4 ? Same as question 1?

In [556]:
A = Matrix([
    [2,6,-2,-8,-6,8],
    [-4,-12,4,16,10,-14],
    [-2,-6,2,8,7,-9],
    [-1,-3,2,3,6,-7]
])


RA = A.rowspace()
print(f'Dimeionsion of rowspace = {len(RA)}\n')
for i in range(len(RA)):
    print(np.array(RA)[i].T,'\n')
print('-'*20)

NA = A.nullspace()
print(f'Dimeionsion of nullspace = {len(NA)}\n')
for i in range(len(NA)):
    print(np.array(NA)[i],'\n')
print('-'*20)
-2  
CA = A.columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

Dimeionsion of rowspace = 3

[[2]
 [6]
 [-2]
 [-8]
 [-6]
 [8]] 

[[0]
 [0]
 [2]
 [-2]
 [6]
 [-6]] 

[[0]
 [0]
 [0]
 [0]
 [2]
 [-2]] 

--------------------
Dimeionsion of nullspace = 3

[[-3]
 [1]
 [0]
 [0]
 [0]
 [0]] 

[[5]
 [0]
 [1]
 [1]
 [0]
 [0]] 

[[-1]
 [0]
 [0]
 [0]
 [1]
 [1]] 

--------------------
Dimeionsion of columnspace = 3

[[2]
 [-4]
 [-2]
 [-1]] 

[[-2]
 [4]
 [2]
 [2]] 

[[-6]
 [10]
 [7]
 [6]] 

--------------------


## Question 5 
No code for this one