In [22]:
import numpy as np
from sympy import *
from fractions import Fraction

In [23]:
A = np.array([
    [7,-3,1],
    [2,1,-9],
    [9,-6,12],
    [-3,2,-4]
])

Matrix(A).rref()[0]

Matrix([
[1, 0, -2],
[0, 1, -5],
[0, 0,  0],
[0, 0,  0]])

In [24]:
def linearDependence(a,b,c,d):
    print('-'*30)
    a = np.array([a])
    b = np.array([b])
    c = np.array([c])
    d = np.array([d])

    u,v,w,x = symbols('u,v,w,x')
    symbolic = np.array([u,v,w,x])

    A = np.concatenate((a,b,c,d))
    print(A)
    print('  rref 🠗')
    print(np.array(Matrix(A).rref()[0]))
    # check leftnullspace for linear dependence
    # return vector required to reach zero vector if true
    ANul = np.array(Matrix(A.T).nullspace())
    if len(ANul) >= 1:
        print(f'\nDimeionsion of nullspace = {len(ANul)}\n')
        for i in range(len(ANul)):
            cokernel = np.array(ANul)[i]
            print(cokernel)
            print(f'\n{symbolic@cokernel} = 0\n')
        print('-'*30)
        CA = Matrix(A).columnspace()
        print(f'Dimeionsion of columnspace = {len(CA)}\n')
        for i in range(len(CA)):
            print(np.array(CA)[i],'\n')
        print('-'*30)
    else:
        print('\nVectors are linearly independent')
        print('-'*30)


linearDependence(
    [1,7,-3],
    [-9,2,1],
    [12,9,-6],
    [-4,-3,2]
)

------------------------------
[[ 1  7 -3]
 [-9  2  1]
 [12  9 -6]
 [-4 -3  2]]
  rref 🠗
[[1 0 -1/5]
 [0 1 -2/5]
 [0 0 0]
 [0 0 0]]

Dimeionsion of nullspace = 2

[[-21/13]
 [15/13]
 [1]
 [0]]

[-21*u/13 + 15*v/13 + w] = 0

[[7/13]
 [-5/13]
 [0]
 [1]]

[7*u/13 - 5*v/13 + x] = 0

------------------------------
Dimeionsion of columnspace = 2

[[1]
 [-9]
 [12]
 [-4]] 

[[7]
 [2]
 [9]
 [-3]] 

------------------------------


In [25]:
C = np.array([
    [8,6],
    [5,4]
])

D = np.array([
    [2,-3],
    [-2.5,4]
])

b = np.array([[2,-1]]).T

print(np.linalg.inv(C)@b)
print(D@b)

A = np.concatenate((C,b),axis=1)

print(A)
Matrix(A).rref()[0]

[[ 7.]
 [-9.]]
[[ 7.]
 [-9.]]
[[ 8  6  2]
 [ 5  4 -1]]


Matrix([
[1, 0,  7],
[0, 1, -9]])

In [26]:
A = Matrix([
    [3,-1,7,3],
    [-2,2,-2,7],
    [-5,9,3,3],
    [1,1,5,10],
    [5,-3,9,-4]
])

CA = A.T.columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

NA = A.nullspace()
print(f'Dimeionsion of nullspace = {len(NA)}\n')
for i in range(len(NA)):
    print(np.array(NA)[i],'\n')
print('-'*20)

Dimeionsion of columnspace = 3

[[3]
 [-1]
 [7]
 [3]] 

[[-2]
 [2]
 [-2]
 [7]] 

[[-5]
 [9]
 [3]
 [3]] 

--------------------
Dimeionsion of nullspace = 1

[[-3]
 [-2]
 [1]
 [0]] 

--------------------


In [27]:
A = np.array([
    [1,-3,3],
    [3,-5,3],
    [6,-6,4]
])

v = np.array([1,1,2])

print(A@v)

[4 4 8]


In [28]:
A = np.array([
    [-5,2],
    [-7,4]
])

L,V = np.linalg.eig(A)

print()
print(np.trace(A))
print(L,V)

x = symbols('x')

(-5-2)*(4-2)


-1
[-3.  2.] [[-0.70710678 -0.27472113]
 [-0.70710678 -0.96152395]]


-14

In [29]:
A = np.array([
    [7,3],
    [3,-1]
])

λ = -2

Matrix((A - λ*np.eye(np.shape(A)[0],dtype=int))).nullspace()[0]



Matrix([
[-1/3],
[   1]])

In [30]:
print(Matrix(A).eigenvects())

v = np.array([-1/3,1])

print(A@v)
print(λ*v)

[(-2, 1, [Matrix([
[-1/3],
[   1]])]), (8, 1, [Matrix([
[3],
[1]])])]
[ 0.66666667 -2.        ]
[ 0.66666667 -2.        ]


In [31]:


b = u - v
print((b.T@b)**0.5)
print(np.linalg.norm(b))

print(u@v)
print(u@w)
print(v@w)

NameError: name 'u' is not defined

In [32]:
x,y,z = symbols('x,y,z')

p1 = np.array([-2,1,1])
p2 = np.array([3,4,1])
p3 = np.array([1,2,0])

P1 = p1 - p2
P2 = p3 - p2 
P3 = np.cross(P1,P2)

print(P1)
print(P2)
print(P3)

a,b,c = P3[0],P3[1],P3[2]

eq = a*x+b*y+c*z

x,y,z = p2[0],p2[1],p2[2]

d = a*x+b*y+c*z

x,y,z = symbols('x,y,z')

eq = a*x+b*y+c*z - d

eq


[-5 -3  0]
[-2 -2 -1]
[ 3 -5  4]


3*x - 5*y + 4*z + 7

In [33]:
t = symbols('t')
# Point P
P = np.array([0,0,1])
# Directional vector d, calling a
d = np.array([-1,5,0]) 
# Created using point P and direction vector
L = P-(t*d)

print(L)

x,y,z = L[0],L[1],L[2]

# Given equation that defines the plane T
T = 3*x - +2*z
# Find t
t = solve(T)[0]
print(t)
# Plug t back into original equation for line to find Q
Q = Matrix(P-(t*d))

Q

[t -5*t 1]
2/3


Matrix([
[  2/3],
[-10/3],
[    1]])

In [34]:
A = np.array([
    [1,-1,1],
    [2,1,1],
    [9,3,1]
])

b = np.array([[-2,4,2]]).T

B = np.linalg.inv(A.T@A)@A.T

with np.printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())}):
    print(B@b)

x = B@b

a1 = np.array([1,-1,1])
a2 = np.array([2,1,1])
a3 = np.array([9,3,1])

print(a1@x)
print(a2@x)
print(a3@x)

print(A@x)

[[-4/3]
 [11/3]
 [3]]
[-2.]
[4.]
[2.]
[[-2.]
 [ 4.]
 [ 2.]]


In [36]:
A = np.array([
    [1,-1,1,-2],
    [2,1,1,4],
    [9,3,1,2]
])

Matrix(A).rref()[0]

Matrix([
[1, 0, 0, -4/3],
[0, 1, 0, 11/3],
[0, 0, 1,    3]])