In [3]:
import numpy as np
from sympy import *

In [5]:
A = np.array([
    [7,-3,1],
    [2,1,-9],
    [9,-6,12],
    [-3,2,-4]
])

Matrix(A).rref()[0]

Matrix([
[1, 0, -2],
[0, 1, -5],
[0, 0,  0],
[0, 0,  0]])

In [120]:
def linearDependence(a,b,c,d):
    print('-'*30)
    a = np.array([a])
    b = np.array([b])
    c = np.array([c])
    d = np.array([d])

    u,v,w,x = symbols('u,v,w,x')
    symbolic = np.array([u,v,w,x])

    A = np.concatenate((a,b,c,d))
    print(A)
    print('  rref 🠗')
    print(np.array(Matrix(A).rref()[0]))
    # check leftnullspace for linear dependence
    # return vector required to reach zero vector if true
    ANul = np.array(Matrix(A.T).nullspace())
    if len(ANul) >= 1:
        print(f'\nDimeionsion of nullspace = {len(ANul)}\n')
        for i in range(len(ANul)):
            cokernel = np.array(ANul)[i]
            print(cokernel)
            print(f'\n{symbolic@cokernel} = 0\n')
        print('-'*30)
        CA = Matrix(A).columnspace()
        print(f'Dimeionsion of columnspace = {len(CA)}\n')
        for i in range(len(CA)):
            print(np.array(CA)[i],'\n')
        print('-'*30)
    else:
        print('\nVectors are linearly independent')
        print('-'*30)


linearDependence(
    [1,7,-3],
    [-9,2,1],
    [12,9,-6],
    [-4,-3,2]
)

------------------------------
[[ 1  7 -3]
 [-9  2  1]
 [12  9 -6]
 [-4 -3  2]]
  rref 🠗
[[1 0 -1/5]
 [0 1 -2/5]
 [0 0 0]
 [0 0 0]]

Dimeionsion of nullspace = 2

[[-21/13]
 [15/13]
 [1]
 [0]]

[-21*u/13 + 15*v/13 + w] = 0

[[7/13]
 [-5/13]
 [0]
 [1]]

[7*u/13 - 5*v/13 + x] = 0

------------------------------
Dimeionsion of columnspace = 2

[[1]
 [-9]
 [12]
 [-4]] 

[[7]
 [2]
 [9]
 [-3]] 

------------------------------
