In [56]:
import numpy as np
from sympy import *

In [57]:
A = np.array([
    [7,-3,1],
    [2,1,-9],
    [9,-6,12],
    [-3,2,-4]
])

Matrix(A).rref()[0]

Matrix([
[1, 0, -2],
[0, 1, -5],
[0, 0,  0],
[0, 0,  0]])

In [58]:
def linearDependence(a,b,c,d):
    print('-'*30)
    a = np.array([a])
    b = np.array([b])
    c = np.array([c])
    d = np.array([d])

    u,v,w,x = symbols('u,v,w,x')
    symbolic = np.array([u,v,w,x])

    A = np.concatenate((a,b,c,d))
    print(A)
    print('  rref 🠗')
    print(np.array(Matrix(A).rref()[0]))
    # check leftnullspace for linear dependence
    # return vector required to reach zero vector if true
    ANul = np.array(Matrix(A.T).nullspace())
    if len(ANul) >= 1:
        print(f'\nDimeionsion of nullspace = {len(ANul)}\n')
        for i in range(len(ANul)):
            cokernel = np.array(ANul)[i]
            print(cokernel)
            print(f'\n{symbolic@cokernel} = 0\n')
        print('-'*30)
        CA = Matrix(A).columnspace()
        print(f'Dimeionsion of columnspace = {len(CA)}\n')
        for i in range(len(CA)):
            print(np.array(CA)[i],'\n')
        print('-'*30)
    else:
        print('\nVectors are linearly independent')
        print('-'*30)


linearDependence(
    [1,7,-3],
    [-9,2,1],
    [12,9,-6],
    [-4,-3,2]
)

------------------------------
[[ 1  7 -3]
 [-9  2  1]
 [12  9 -6]
 [-4 -3  2]]
  rref 🠗
[[1 0 -1/5]
 [0 1 -2/5]
 [0 0 0]
 [0 0 0]]

Dimeionsion of nullspace = 2

[[-21/13]
 [15/13]
 [1]
 [0]]

[-21*u/13 + 15*v/13 + w] = 0

[[7/13]
 [-5/13]
 [0]
 [1]]

[7*u/13 - 5*v/13 + x] = 0

------------------------------
Dimeionsion of columnspace = 2

[[1]
 [-9]
 [12]
 [-4]] 

[[7]
 [2]
 [9]
 [-3]] 

------------------------------


In [59]:
C = np.array([
    [8,6],
    [5,4]
])

D = np.array([
    [2,-3],
    [-2.5,4]
])

b = np.array([[2,-1]]).T

print(np.linalg.inv(C)@b)
print(D@b)

A = np.concatenate((C,b),axis=1)

print(A)
Matrix(A).rref()[0]

[[ 7.]
 [-9.]]
[[ 7.]
 [-9.]]
[[ 8  6  2]
 [ 5  4 -1]]


Matrix([
[1, 0,  7],
[0, 1, -9]])

In [62]:
A = Matrix([
    [3,-1,7,3],
    [-2,2,-2,7],
    [-5,9,3,3],
    [1,1,5,10],
    [5,-3,9,-4]
])

CA = A.T.columnspace()
print(f'Dimeionsion of columnspace = {len(CA)}\n')
for i in range(len(CA)):
    print(np.array(CA)[i],'\n')
print('-'*20)

NA = A.nullspace()
print(f'Dimeionsion of nullspace = {len(NA)}\n')
for i in range(len(NA)):
    print(np.array(NA)[i],'\n')
print('-'*20)

Dimeionsion of columnspace = 3

[[3]
 [-1]
 [7]
 [3]] 

[[-2]
 [2]
 [-2]
 [7]] 

[[-5]
 [9]
 [3]
 [3]] 

--------------------
Dimeionsion of nullspace = 1

[[-3]
 [-2]
 [1]
 [0]] 

--------------------


In [64]:
A = np.array([
    [1,-3,3],
    [3,-5,3],
    [6,-6,4]
])

v = np.array([1,1,2])

print(A@v)

[4 4 8]


In [82]:
A = np.array([
    [-5,2],
    [-7,4]
])

L,V = np.linalg.eig(A)

print()
print(np.trace(A))
print(L,V)

x = symbols('x')

(-5-2)*(4-2)


-1
[-3.  2.] [[-0.70710678 -0.27472113]
 [-0.70710678 -0.96152395]]


-14

In [93]:
A = np.array([
    [7,3],
    [3,-1]
])

λ = -2

Matrix((A - λ*np.eye(np.shape(A)[0],dtype=int))).nullspace()[0]



Matrix([
[-1/3],
[   1]])

In [107]:
print(Matrix(A).eigenvects())

v = np.array([-1/3,1])

print(A@v)
print(λ*v)

[(-2, 1, [Matrix([
[-1/3],
[   1]])]), (8, 1, [Matrix([
[3],
[1]])])]
[ 0.66666667 -2.        ]
[ 0.66666667 -2.        ]


In [108]:
u = np.array([-2,1,1])
v = np.array([3,4,1])
w = np.array([1,2,0])

print(u-v)

[-5 -3  0]
