In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [3]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]

rb = np.linalg.matrix_rank(B)
# print('rank = ' + str(rb))

rank = 4


In [7]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 29
rank (with noise) = 30


In [10]:
m = 10
n = 4

A = np.round( 10*np.random.randn(m,m) )
B = A.T

print(A)
print('')
print(B)


[[ 2.65918774 -0.96547627 -0.77884071  0.0430701 ]
 [-1.32766044 -1.76819781 -0.63532685  0.19682309]
 [-1.60932502 -0.17233027  0.47846307  0.26939936]
 [-0.35318914  0.30201433 -0.22017559  1.70922099]
 [-1.39450226  1.72019848 -1.64099243 -1.178563  ]
 [ 0.88654249 -0.07915646 -0.57273571  0.41178429]
 [ 0.41183376 -1.00315424  0.29378724  1.83309784]
 [-1.07269099 -1.79173506  0.88287981  1.06282745]
 [ 0.22352775  0.19679166  0.32450764 -0.23315918]
 [-1.32550249  0.04996725 -0.62201032  0.40404345]]

[[ 2.65918774 -1.32766044 -1.60932502 -0.35318914 -1.39450226  0.88654249
   0.41183376 -1.07269099  0.22352775 -1.32550249]
 [-0.96547627 -1.76819781 -0.17233027  0.30201433  1.72019848 -0.07915646
  -1.00315424 -1.79173506  0.19679166  0.04996725]
 [-0.77884071 -0.63532685  0.47846307 -0.22017559 -1.64099243 -0.57273571
   0.29378724  0.88287981  0.32450764 -0.62201032]
 [ 0.0430701   0.19682309  0.26939936  1.70922099 -1.178563    0.41178429
   1.83309784  1.06282745 -0.23315918  


---
# VIDEO: Rank of A^TA and AA^T
---


In [5]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [6]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30
